spring:
  data:
    mongodb:
      port: 27017
      host: 172.17.0.2
      database: notifications-service

---

spring:
  profiles: kubernetes
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
          zkNodes: ${KAFKA_ZOOKEEPER_NODES}
  data:
    mongodb:
      port: ${MONGO_DATABASE_PORT}
      host: ${MONGO_DATABASE_HOST}
      username: ${MONGO_DATABASE_USERNAME}
      password: ${MONGO_DATABASE_PASSWORD}
